stages:
  - test
  - verify-import

run-pytest:
  stage: test
  script: 
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - pytest

verify-latest-importable:
  stage: verify-import
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install git+https://gitlab.com/mnhs/bipi/datagenius.git@latest#egg=data-genius 
