compound_fnames:
  - mary ann
  - jo ann
  - mary beth
  - mary lo?u
  - mary jane
  - lee ann
  - mary jo
  - lo?u ann
  - mary kay
  - mary ellen
  - mary alice
  - mary kate
  - ann[ae]? marie
  - betty lo?u 
  - rae ann
  - rae jean
  - polly ann

lname_particles:
  - v[ao]n$
  - ver$
  - de[rnl]$
  - de$ 
  - l[ao]s$
  - vau$
  - zie$
  - st\.?$
  - o$
  - ma?c$
  - vande[rn]$
  - della$

invalid_words:
  - the
  - family
  - subscriber
  - cpa
  - dds
  - usmc
  - esq
  - international
  - college 